service: cognito-one-time-password-template

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-plugin-typescript

functions:
  defineAuth:
    handler: src/handlers/defineAuth.handle
  createAuth:
    handler: src/handlers/createAuth.handle
  verifyAuth:
    handler: src/handlers/verifyAuth.handle
  preSignUp:
    handler: src/handlers/preSignUp.handle
